spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dsatracker
    username: postgres
    password: Pratham@21
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: "dsa-tracker-super-secret-key-256bits-minimum-length"
  expiration-ms: 86400000

server:
  port: 8080