spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dsatracker
    username: your_db_username
    password: your_db_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: "your-secret-key-minimum-32-characters-long"
  expiration-ms: 86400000

server:
  port: 8080